trigger:
- main

variables:
  solutionDir: 'src/Writings.Api'
  unitTestSolutionDir: 'test/Writings.Application.Tests.Unit'
  integrationTestSolutionDir: 'test/Writings.Api.Tests.Integration'

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: build
    steps:
    - script: pwd
      displayName: 'what directory are we in?'

    - script: ls -la
      displayName: 'what files are in this folder?'

    - script: docker --version
      displayName: 'docker version'
      workingDirectory: $(solutionDir)

    - script: dotnet build 
      displayName: 'dotnet-build'
      workingDirectory: $(solutionDir)

    - task: DotNetCoreCLI@2
      displayName: 'run unit tests'
      inputs:
        command: 'test'
        workingDirectory: $(unitTestSolutionDir)
    
    - task: DotNetCoreCLI@2
      displayName: 'run integration tests'
      inputs:
        command: 'test'
        workingDirectory: $(integrationTestSolutionDir)

    - script: dotnet publish -o $(build.artifactStagingDirectory) 
      displayName: 'dotnet publish -o $(build.artifactStagingDirectory) '
      workingDirectory: $(solutionDir)

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(build.artifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'
