# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  solutionDir: 'src/Writings.Api'

pool:
  vmImage: ubuntu-latest

steps:
- script: pwd
  displayName: 'what directory are we in?'

- script: ls -la
  displayName: 'what files are in this folder?'

- script: dotnet build 
  displayName: 'dotnet-build'
  workingDirectory: $(solutionDir)

- script: dotnet publish -o $(build.artifactStagingDirectory) 
  displayName: 'dotnet publish -o $(build.artifactStagingDirectory) '
  workingDirectory: $(solutionDir)

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'
